language: rust
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/.cargo
    - $HOME/.rustup

before_cache:
  - rm -rf $HOME/.cargo/registry

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

before_install:
  - sudo add-apt-repository -y ppa:0k53d-karl-f830m/openssl
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libelf-dev libdw-dev cmake gcc binutils-dev libiberty-dev


script:
  - cargo check --all
  - cargo test --all --no-fail-fast
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clippy
    fi